services:
  neo4j:
    image: neo4j:2025.06.0
    ports:
      - "7474:7474"   # Port HTTP (browser)
      - "7687:7687"   # Port Bolt (driver)
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j-data:/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # HTTP API
      - "6334:6334" # gRPC API
    volumes:
      - qdrant-data:/qdrant/storage

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_INITDB_DATABASE: db0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NEO4J_URL: bolt://neo4j:7687
      QDRANT_URL: http://qdrant:6333
    command: celery -A workers.tasks worker --loglevel=INFO
    volumes:
      - ./:/app
    depends_on:
      - mongo
      - neo4j
      - qdrant

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NEO4J_URL: bolt://neo4j:7687
      QDRANT_URL: http://qdrant:6333
      MONGO_URI: mongodb://root:pwd@mongo:27017/?authSource=admin
    ports:
      - "8000:8000"
    command: fastapi dev main.py --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    depends_on:
      - worker

volumes:
  neo4j-data:
  mongodb-data:
  qdrant-data: